// Thai refinery crude/condensate intake, 2026 extract (DOEB / PEIT source sheet).
// [month, crude, origin, region, company, volume, type]
window.CRUDE_ROWS = [
["Jan","Arabian Extra Light","Saudi Arabia","Middle East","SPRC",162.93,"Crude"],
["Jan","Arabian Light","Saudi Arabia","Middle East","IRPC",409.14,"Crude"],
["Jan","Arabian Light","Saudi Arabia","Middle East","THAI OIL",399.70,"Crude"],
["Jan","Banyu Urip","Indonesia","Far East","BCP",44.26,"Crude"],
["Jan","Banyu Urip","Indonesia","Far East","BSRC",28.00,"Crude"],
["Jan","Bintulu","Malaysia","Far East","BSRC",48.20,"Crude"],
["Jan","Bunga Orkid","Malaysia","Far East","BCP",50.42,"Crude"],
["Jan","Champion","Brunei","Far East","BCP",48.36,"Crude"],
["Jan","Das","UAE","Middle East","IRPC",153.09,"Crude"],
["Jan","Das","UAE","Middle East","THAI OIL",76.32,"Crude"],
["Jan","Golden Arrowhead","Guyana","Other","PTTGC",113.10,"Crude"],
["Jan","Hai Thach Cond.","Vietnam","Far East","BSRC",32.11,"Crude"],
["Jan","Khafji","Saudi Arabia","Middle East","BSRC",60.82,"Crude"],
["Jan","Kimanis Cond.","Malaysia","Far East","BCP",92.78,"Condensate"],
["Jan","Kuwait","Kuwait","Middle East","BSRC",64.12,"Crude"],
["Jan","Kuwait Super Light","Kuwait","Middle East","BSRC",48.57,"Crude"],
["Jan","Labuan","Malaysia","Far East","THAI OIL",48.27,"Crude"],
["Jan","Midland Sweet","USA","Other","BSRC",166.29,"Crude"],
["Jan","Murban","UAE","Middle East","BCP",48.97,"Crude"],
["Jan","Murban","UAE","Middle East","THAI OIL",160.55,"Crude"],
["Jan","Murban","UAE","Middle East","BSRC",123.06,"Crude"],
["Jan","Murban","UAE","Middle East","PTTGC",76.48,"Crude"],
["Jan","Murban","UAE","Middle East","SPRC",629.57,"Crude"],
["Jan","Murban","UAE","Middle East","THAI OIL",561.03,"Crude"],
["Jan","Nile Blend","Sudan","Other","BCP",45.78,"Crude"],
["Jan","Okwuibome","Nigeria","Other","BSRC",75.84,"Crude"],
["Jan","Okwuibome","Nigeria","Other","THAI OIL",76.56,"Crude"],
["Jan","Pakistan Cond.","Pakistan","Other","BCP",51.55,"Condensate"],
["Jan","Pangkah","Indonesia","Far East","PTTGC",30.01,"Crude"],
["Jan","Sarir Mesla Blend","Libya","Other","BSRC",53.15,"Crude"],
["Jan","Seria Light","Brunei","Far East","BSRC",48.04,"Crude"],
["Jan","Sumatran Light","Indonesia","Far East","PTTGC",31.58,"Crude"],
["Jan","Tapis Blend","Malaysia","Far East","SPRC",60.16,"Crude"],
["Jan","Umm Lulu","UAE","Middle East","THAI OIL",156.47,"Crude"],
["Jan","Umm Lulu","UAE","Middle East","THAI OIL",152.28,"Crude"],
["Jan","Upper Zakum","UAE","Middle East","SPRC",76.41,"Crude"],
["Jan","Windy Ridge","USA","Other","BCP",32.20,"Crude"],
["Jan","Windy Ridge","USA","Other","BSRC",20.94,"Crude"],
["Jan","WTI Midland","USA","Other","IRPC",238.48,"Crude"],
["Jan","WTI Midland","USA","Other","PTT",80.60,"Crude"],
["Jan","WTI Midland","USA","Other","PTTGC",305.59,"Crude"],
["Jan","WTI Midland","USA","Other","THAI OIL",49.10,"Crude"],
["Feb","Arabian Light","Saudi Arabia","Middle East","IRPC",402.85,"Crude"],
["Feb","Arabian Light","Saudi Arabia","Middle East","THAI OIL",160.70,"Crude"],
["Feb","Belida","Indonesia","Far East","PTTGC",30.16,"Crude"],
["Feb","Bintulu","Malaysia","Far East","BCP",45.87,"Crude"],
["Feb","Bunga Kekwa","Malaysia","Far East","THAI OIL",46.78,"Crude"],
["Feb","Bunga Orkid","Malaysia","Far East","BCP",46.83,"Crude"],
["Feb","Cendor","Malaysia","Far East","BCP",48.39,"Crude"],
["Feb","Champion","Brunei","Far East","BSRC",53.08,"Crude"],
["Feb","Cossack","Australia","Other","BCP",50.49,"Crude"],
["Feb","Cossack","Australia","Other","BSRC",59.20,"Crude"],
["Feb","Das","UAE","Middle East","IRPC",152.74,"Crude"],
["Feb","Forel","Indonesia","Far East","BCP",38.79,"Crude"],
["Feb","Golden Arrowhead","Guyana","Other","PTTGC",120.84,"Crude"],
["Feb","Khafji","Saudi Arabia","Middle East","BSRC",63.94,"Crude"],
["Feb","Kimanis Cond.","Malaysia","Far East","BCP",92.60,"Condensate"],
["Feb","Labuan","Malaysia","Far East","BCP",49.16,"Crude"],
["Feb","Labuan","Malaysia","Far East","PTTGC",49.92,"Crude"],
["Feb","Medanito","Argentina","Other","BCP",50.65,"Crude"],
["Feb","Medanito","Argentina","Other","BSRC",67.48,"Crude"],
["Feb","Medanito","Argentina","Other","PTTGC",48.00,"Crude"],
["Feb","Meleck","Niger","Other","PTTGC",167.52,"Crude"],
["Feb","Mero","Brazil","Other","PTTGC",31.90,"Crude"],
["Feb","Midland Sweet","USA","Other","BSRC",176.72,"Crude"],
["Feb","Murban","UAE","Middle East","THAI OIL",248.68,"Crude"],
["Feb","Murban","UAE","Middle East","BSRC",88.23,"Crude"],
["Feb","Murban","UAE","Middle East","IRPC",84.17,"Crude"],
["Feb","Murban","UAE","Middle East","THAI OIL",560.56,"Crude"],
["Feb","Qatar Marine","Qatar","Middle East","IRPC",80.28,"Crude"],
["Feb","Qatar Marine","Qatar","Middle East","PTT",84.19,"Crude"],
["Feb","Sarir Mesla Blend","Libya","Other","BSRC",165.16,"Crude"],
["Feb","Seria Light","Brunei","Far East","BSRC",48.50,"Crude"],
["Feb","Tapis Blend","Malaysia","Far East","SPRC",25.90,"Crude"],
["Feb","Thang Long","Vietnam","Far East","BCP",42.99,"Crude"],
["Feb","Umm Lulu","UAE","Middle East","THAI OIL",76.27,"Crude"],
["Feb","Umm Lulu","UAE","Middle East","IRPC",77.48,"Crude"],
["Feb","Umm Lulu","UAE","Middle East","THAI OIL",244.75,"Crude"],
["Feb","WTI Midland","USA","Other","BCP",75.98,"Crude"],
["Feb","WTI Midland","USA","Other","IRPC",219.17,"Crude"],
["Mar","Arabian Light","Saudi Arabia","Middle East","SPRC",164.87,"Crude"],
["Mar","Arabian Light","Saudi Arabia","Middle East","IRPC",75.07,"Crude"],
["Mar","Banyu Urip","Indonesia","Far East","BCP",50.56,"Crude"],
["Mar","Banyu Urip","Indonesia","Far East","BSRC",50.57,"Crude"],
["Mar","Belida","Indonesia","Far East","BCP",21.06,"Crude"],
["Mar","Bertam","Malaysia","Far East","PTTGC",41.58,"Crude"],
["Mar","Bu Attifel","Libya","Other","IRPC",43.25,"Crude"],
["Mar","Bunga Orkid","Malaysia","Far East","BCP",48.45,"Crude"],
["Mar","Champion","Brunei","Far East","BCP",32.30,"Crude"],
["Mar","Champion","Brunei","Far East","BSRC",16.11,"Crude"],
["Mar","Das","UAE","Middle East","IRPC",83.91,"Crude"],
["Mar","Das","UAE","Middle East","THAI OIL",80.24,"Crude"],
["Mar","Dulang","Malaysia","Far East","BCP",48.49,"Crude"],
["Mar","Forel","Indonesia","Far East","BCP",19.97,"Crude"],
["Mar","Hai Thach Cond.","Vietnam","Far East","PTTGC",29.27,"Condensate"],
["Mar","Iracema","Brazil","Other","PTTGC",152.23,"Crude"],
["Mar","Khafji","Saudi Arabia","Middle East","BSRC",64.16,"Crude"],
["Mar","Kuwait Super Light","Kuwait","Middle East","BSRC",88.94,"Crude"],
["Mar","Labuan","Malaysia","Far East","PTTGC",48.99,"Crude"],
["Mar","Lalang","Indonesia","Far East","PTTGC",18.00,"Crude"],
["Mar","Midland Sweet","USA","Other","BSRC",170.26,"Crude"],
["Mar","Montara","Australia","Other","BCP",74.72,"Crude"],
["Mar","Murban","UAE","Middle East","BCP",45.91,"Crude"],
["Mar","Murban","UAE","Middle East","SPRC",580.23,"Crude"],
["Mar","Murban","UAE","Middle East","THAI OIL",80.79,"Crude"],
["Mar","Murban","UAE","Middle East","BSRC",22.89,"Crude"],
["Mar","Murban","UAE","Middle East","IRPC",422.09,"Crude"],
["Mar","Murban","UAE","Middle East","THAI OIL",793.48,"Crude"],
["Mar","Sarir Mesla Blend","Libya","Other","BSRC",254.09,"Crude"],
["Mar","Tapis Blend","Malaysia","Far East","PTTGC",55.85,"Crude"],
["Mar","Tapis Blend","Malaysia","Far East","SPRC",49.59,"Crude"],
["Mar","Umm Lulu","UAE","Middle East","THAI OIL",84.22,"Crude"],
["Mar","Umm Lulu","UAE","Middle East","PTTGC",83.61,"Crude"],
["Mar","Umm Lulu","UAE","Middle East","THAI OIL",317.53,"Crude"],
["Mar","Upper Zakum","UAE","Middle East","SPRC",80.70,"Crude"],
["Mar","Upper Zakum","UAE","Middle East","IRPC",83.89,"Crude"],
["Mar","Upper Zakum","UAE","Middle East","THAI OIL",84.59,"Crude"],
["Mar","Windy Ridge Cond.","USA","Other","BCP",74.71,"Condensate"],
["Mar","Windy Ridge Cond.","USA","Other","BSRC",31.71,"Condensate"],
["Mar","WTI Midland","USA","Other","IRPC",332.05,"Crude"],
["Mar","WTI Midland","USA","Other","PTTGC",162.15,"Crude"],
["Apr","Agbami","Nigeria","Other","SPRC",165.34,"Crude"],
["Apr","Arabian Light","Saudi Arabia","Middle East","IRPC",163.22,"Crude"],
["Apr","Arabian Light","Saudi Arabia","Middle East","THAI OIL",163.45,"Crude"],
["Apr","Banyu Urip","Indonesia","Far East","BCP",45.73,"Crude"],
["Apr","Banyu Urip","Indonesia","Far East","BSRC",54.70,"Crude"],
["Apr","Belanak","Indonesia","Far East","BSRC",24.60,"Crude"],
["Apr","Belida","Indonesia","Far East","PTTGC",23.60,"Crude"],
["Apr","Bunga Kekwa","Malaysia","Far East","IRPC",50.00,"Crude"],
["Apr","Bunga Orkid","Malaysia","Far East","THAI OIL",45.91,"Crude"],
["Apr","Buzios","Brazil","Other","BSRC",51.55,"Crude"],
["Apr","Cabinda","Angola","Other","PTTGC",154.52,"Crude"],
["Apr","Champion","Brunei","Far East","BSRC",96.66,"Crude"],
["Apr","Champion","Brunei","Far East","SPRC",45.97,"Crude"],
["Apr","Clov","Angola","Other","PTTGC",136.77,"Crude"],
["Apr","Clov","Angola","Other","THAI OIL",28.54,"Crude"],
["Apr","Dulang","Malaysia","Far East","BCP",45.79,"Crude"],
["Apr","Forel","Indonesia","Far East","PTTGC",20.49,"Crude"],
["Apr","Girassol","Angola","Other","THAI OIL",168.35,"Crude"],
["Apr","Hai Thach Cond.","Vietnam","Far East","PTTGC",33.68,"Condensate"],
["Apr","Ichthys Cond.","Australia","Other","BSRC",52.24,"Condensate"],
["Apr","Jones Creek","Nigeria","Other","THAI OIL",168.09,"Crude"],
["Apr","Khafji","Saudi Arabia","Middle East","BSRC",61.06,"Crude"],
["Apr","Kidurong","Malaysia","Far East","BCP",50.16,"Crude"],
["Apr","Lalang","Indonesia","Far East","PTTGC",32.63,"Crude"],
["Apr","Medanito","Argentina","Other","BCP",50.70,"Crude"],
["Apr","Medanito","Argentina","Other","BSRC",72.10,"Crude"],
["Apr","Medanito","Argentina","Other","PTTGC",48.07,"Crude"],
["Apr","Midland Sweet","USA","Other","BSRC",160.36,"Crude"],
["Apr","Murban","UAE","Middle East","SPRC",164.89,"Crude"],
["Apr","Murban","UAE","Middle East","BSRC",51.76,"Crude"],
["Apr","Murban","UAE","Middle East","THAI OIL",267.53,"Crude"],
["Apr","Pazflor","Angola","Other","THAI OIL",16.34,"Crude"],
["Apr","Pazflor","Angola","Other","THAI OIL",136.90,"Crude"],
["Apr","Qua Iboe","Nigeria","Other","SPRC",80.47,"Crude"],
["Apr","Ruby","Vietnam","Far East","BCP",50.50,"Crude"],
["Apr","Sarir Mesla Blend","Libya","Other","BSRC",167.11,"Crude"],
["Apr","Sarir Mesla Blend","Libya","Other","IRPC",169.30,"Crude"],
["Apr","Sarir Mesla Blend","Libya","Other","THAI OIL",168.45,"Crude"],
["Apr","Seria Light","Brunei","Far East","BCP",48.52,"Crude"],
["Apr","Sumatran Light","Indonesia","Far East","PTTGC",16.40,"Crude"],
["Apr","Windy Ridge Cond.","USA","Other","BSRC",56.57,"Condensate"],
["Apr","WTI Midland","USA","Other","BCP",80.41,"Crude"],
["Apr","WTI Midland","USA","Other","IRPC",171.08,"Crude"],
["Apr","WTI Midland","USA","Other","PTTGC",121.15,"Crude"],
["May","Arabian Light","Saudi Arabia","Middle East","IRPC",570.47,"Crude"],
["May","Arabian Light","Saudi Arabia","Middle East","THAI OIL",327.59,"Crude"],
["May","Aseng","Equatorial Guinea","Other","IRPC",108.26,"Crude"],
["May","Azeri BTC","Azerbaijan","Other","BSRC",168.88,"Crude"],
["May","Baleine","Ivory Coast","Other","THAI OIL",126.58,"Crude"],
["May","Belanak","Indonesia","Far East","BCP",17.63,"Crude"],
["May","Belida","Indonesia","Far East","BSRC",21.07,"Crude"],
["May","Bunga Kekwa","Malaysia","Far East","SPRC",48.07,"Crude"],
["May","Champion","Brunei","Far East","BSRC",48.00,"Crude"],
["May","Chim Sao","Vietnam","Far East","BCP",42.30,"Crude"],
["May","Coco","Congo","Other","THAI OIL",144.34,"Crude"],
["May","CPC Blend","Kazakhstan","Other","SPRC",83.82,"Crude"],
["May","Escravos Cond.","Nigeria","Far East","SPRC",169.41,"Condensate"],
["May","Etame","Gabon","Other","IRPC",33.39,"Crude"],
["May","Forel","Indonesia","Far East","PTTGC",21.04,"Crude"],
["May","Forties","United Kingdom","Other","PTTGC",36.19,"Crude"],
["May","Forties","United Kingdom","Other","PTTGC",77.37,"Crude"],
["May","Golden Arrowhead","Guyana","Other","THAI OIL",160.63,"Crude"],
["May","Hai Thach Cond.","Vietnam","Far East","PTTGC",33.40,"Condensate"],
["May","Labuan","Malaysia","Far East","BCP",46.45,"Crude"],
["May","Maari","New Zealand","Other","SPRC",72.83,"Crude"],
["May","Medanito","Argentina","Other","BCP",50.15,"Crude"],
["May","Medanito","Argentina","Other","BSRC",69.54,"Crude"],
["May","Medanito","Argentina","Other","IRPC",40.21,"Crude"],
["May","Medanito","Argentina","Other","PTTGC",76.16,"Crude"],
["May","Miri Light","Malaysia","Far East","IRPC",53.89,"Crude"],
["May","Montara","Australia","Other","BCP",46.94,"Crude"],
["May","Murban","UAE","Middle East","PTTGC",79.22,"Crude"],
["May","Murban","UAE","Middle East","SPRC",411.26,"Crude"],
["May","Murban","UAE","Middle East","THAI OIL",387.51,"Crude"],
["May","Nile Blend","South Sudan","Other","BSRC",50.25,"Crude"],
["May","Nile Blend","Sudan","Other","BCP",70.55,"Crude"],
["May","Qua Iboe","Nigeria","Other","SPRC",80.41,"Crude"],
["May","Qua Iboe","Nigeria","Other","BSRC",109.16,"Crude"],
["May","Qua Iboe","Nigeria","Other","BCP",50.61,"Crude"],
["May","Sarir Mesla Blend","Libya","Other","BSRC",263.79,"Crude"],
["May","Sarir Mesla Blend","Libya","Other","PTTGC",73.21,"Crude"],
["May","Thang Long","Vietnam","Far East","BSRC",40.17,"Crude"],
["May","Unity Gold","Guyana","Other","THAI OIL",160.57,"Crude"],
["May","Windy Ridge Cond.","USA","Other","BCP",51.85,"Condensate"],
["May","WTI Midland","USA","Other","PTTGC",81.60,"Crude"],
["May","WTI Midland","USA","Other","IRPC",702.21,"Crude"],
["May","WTI Midland","USA","Other","THAI OIL",252.26,"Crude"],
["Jun","Alaska North Slope","USA","Other","IRPC",67.98,"Crude"],
["Jun","Alaska North Slope","USA","Other","PTTGC",46.87,"Crude"],
["Jun","Arabian Light","Saudi Arabia","Middle East","IRPC",161.08,"Crude"],
["Jun","Arabian Light","Saudi Arabia","Middle East","THAI OIL",161.60,"Crude"],
["Jun","Bertam","Malaysia","Far East","BCP",40.36,"Crude"],
["Jun","Bunga Kekwa","Malaysia","Far East","BCP",48.22,"Crude"],
["Jun","Bunga Orkid","Malaysia","Far East","BCP",48.33,"Crude"],
["Jun","Cabinda","Angola","Other","BSRC",105.61,"Crude"],
["Jun","Champion","Brunei","Far East","BSRC",48.13,"Crude"],
["Jun","CPC Blend","Kazakhstan","Other","SPRC",82.22,"Crude"],
["Jun","Das","UAE","Middle East","THAI OIL",156.69,"Crude"],
["Jun","Das","UAE","Middle East","IRPC",168.64,"Crude"],
["Jun","Kimanis Cond.","Malaysia","Far East","THAI OIL",100.80,"Condensate"],
["Jun","Lucina","Gabon","Other","THAI OIL",45.88,"Crude"],
["Jun","Medanito","Argentina","Other","BCP",48.15,"Crude"],
["Jun","Medanito","Argentina","Other","BSRC",69.18,"Crude"],
["Jun","Medanito","Argentina","Other","PTTGC",79.49,"Crude"],
["Jun","Mero","Brazil","Other","PTTGC",151.57,"Crude"],
["Jun","Midland Sweet","USA","Other","BSRC",425.50,"Crude"],
["Jun","Murban","UAE","Middle East","SPRC",236.39,"Crude"],
["Jun","Murban","UAE","Middle East","THAI OIL",84.24,"Crude"],
["Jun","Rabi Export Blend","Gabon","Other","THAI OIL",110.04,"Crude"],
["Jun","Rabi Light","Gabon","Other","PTTGC",147.02,"Crude"],
["Jun","Sarir Mesla Blend","Libya","Other","BCP",72.26,"Crude"],
["Jun","Sepat","Malaysia","Far East","BCP",19.28,"Crude"],
["Jun","Seria Light","Brunei","Far East","BCP",103.55,"Crude"],
["Jun","Seria Light","Brunei","Far East","BSRC",43.56,"Crude"],
["Jun","Umm Lulu","UAE","Middle East","THAI OIL",330.11,"Crude"],
["Jun","West Texas Light","USA","Other","SPRC",80.41,"Crude"],
["Jun","WTI Midland","USA","Other","BCP",85.37,"Crude"],
["Jun","WTI Midland","USA","Other","IRPC",250.82,"Crude"],
["Jun","WTI Midland","USA","Other","PTTGC",80.27,"Crude"],
["Jun","WTI Midland","USA","Other","SPRC",82.11,"Crude"]
];
window.CRUDE_MONTHS = ["Jan","Feb","Mar","Apr","May","Jun"];
window.CRUDE_PARTIAL = ["Jun"];
